// Mocks generated by Mockito 5.4.6 from annotations
// in taabor/test/unit/queue_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:taabor/core/error/failures.dart' as _i5;
import 'package:taabor/features/queue/domain/entities/ticket.dart' as _i6;
import 'package:taabor/features/queue/domain/repositories/queue_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QueueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueRepository extends _i1.Mock implements _i3.QueueRepository {
  MockQueueRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> addTicket(_i6.Ticket? ticket) =>
      (super.noSuchMethod(
            Invocation.method(#addTicket, [ticket]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#addTicket, [ticket]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Ticket>>>
  streamTicketsForBusiness(String? businessId) =>
      (super.noSuchMethod(
            Invocation.method(#streamTicketsForBusiness, [businessId]),
            returnValue:
                _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Ticket>>>.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Ticket>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTicketStatus(
    String? ticketId,
    _i6.TicketStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTicketStatus, [ticketId, status]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateTicketStatus, [ticketId, status]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Ticket>>> getUserTickets(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTickets, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Ticket>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Ticket>>(
                    this,
                    Invocation.method(#getUserTickets, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Ticket>>>);
}
