// Mocks generated by Mockito 5.4.6 from annotations
// in taabor/test/unit/queue_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:taabor/core/services/offline_service.dart' as _i7;
import 'package:taabor/features/queue/data/datasources/queue_remote_data_source.dart'
    as _i2;
import 'package:taabor/features/queue/data/models/ticket_model.dart' as _i4;
import 'package:taabor/features/queue/domain/entities/ticket.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QueueRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueRemoteDataSource extends _i1.Mock
    implements _i2.QueueRemoteDataSource {
  MockQueueRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> addTicket(_i4.TicketModel? ticket) =>
      (super.noSuchMethod(
            Invocation.method(#addTicket, [ticket]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#addTicket, [ticket]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Stream<List<_i4.TicketModel>> streamTicketsForBusiness(
    String? businessId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamTicketsForBusiness, [businessId]),
            returnValue: _i3.Stream<List<_i4.TicketModel>>.empty(),
          )
          as _i3.Stream<List<_i4.TicketModel>>);

  @override
  _i3.Future<void> updateTicketStatus(
    String? ticketId,
    _i6.TicketStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTicketStatus, [ticketId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TicketModel>> getUserTickets(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTickets, [userId]),
            returnValue: _i3.Future<List<_i4.TicketModel>>.value(
              <_i4.TicketModel>[],
            ),
          )
          as _i3.Future<List<_i4.TicketModel>>);
}

/// A class which mocks [OfflineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineService extends _i1.Mock implements _i7.OfflineService {
  MockOfflineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cacheTicket(Map<String, dynamic>? ticketData) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTicket, [ticketData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<Map<dynamic, dynamic>> getCachedTickets() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTickets, []),
            returnValue: <Map<dynamic, dynamic>>[],
          )
          as List<Map<dynamic, dynamic>>);
}
