import 'package:flutter/material.dart';
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
import 'package:taabor/core/services/review_service.dart';
import 'package:taabor/features/engagement/data/models/review.dart';

class RatingDialog extends StatefulWidget {
  final String businessId;
  final String userId;

  const RatingDialog({
    super.key,
    required this.businessId,
    required this.userId,
  });

  @override
  State<RatingDialog> createState() => _RatingDialogState();
}

class _RatingDialogState extends State<RatingDialog> {
  final ReviewService _reviewService = ReviewService();
  double _rating = 3.0;
  final TextEditingController _commentController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Rate your experience'),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text('How was the service?'),
            const SizedBox(height: 16),
            RatingBar.builder(
              initialRating: 3,
              minRating: 1,
              direction: Axis.horizontal,
              allowHalfRating: true,
              itemCount: 5,
              itemPadding: const EdgeInsets.symmetric(horizontal: 4.0),
              itemBuilder: (context, _) =>
                  const Icon(Icons.star, color: Colors.amber),
              onRatingUpdate: (rating) {
                setState(() {
                  _rating = rating;
                });
              },
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _commentController,
              decoration: const InputDecoration(
                hintText: 'Leave a note (optional)',
                border: OutlineInputBorder(),
              ),
              maxLines: 3,
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(), // Close without rating
          child: const Text('Skip'),
        ),
        ElevatedButton(
          onPressed: () async {
            await _reviewService.addReview(
              Review(
                id: '', // Generated by Firestore
                businessId: widget.businessId,
                userId: widget.userId,
                rating: _rating,
                comment: _commentController.text.trim(),
                timestamp: DateTime.now(),
              ),
            );
            if (context.mounted) {
              Navigator.of(context).pop();
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Thank you for your feedback!')),
              );
            }
          },
          child: const Text('Submit'),
        ),
      ],
    );
  }
}
