// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEzT3EgCYgHqYJYLZXt8m07K1GvY-ZegY',
    appId: '1:332519555718:web:61fbb62c6aa259275c4707',
    messagingSenderId: '332519555718',
    projectId: 'taabor-mobile-app',
    authDomain: 'taabor-mobile-app.firebaseapp.com',
    storageBucket: 'taabor-mobile-app.firebasestorage.app',
    measurementId: 'G-CCX53F2FRK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD65V-q6TTMfqTyJvfl-Zj_6Gbi0k8wV4M',
    appId: '1:332519555718:ios:79e38a7320c979435c4707',
    messagingSenderId: '332519555718',
    projectId: 'taabor-mobile-app',
    storageBucket: 'taabor-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65V-q6TTMfqTyJvfl-Zj_6Gbi0k8wV4M',
    appId: '1:332519555718:ios:79e38a7320c979435c4707',
    messagingSenderId: '332519555718',
    projectId: 'taabor-mobile-app',
    storageBucket: 'taabor-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbaJ-8p6zuIvHmmoWVnkRM-QFajNydKU',
    appId: '1:332519555718:android:3b4999dd4cee536c5c4707',
    messagingSenderId: '332519555718',
    projectId: 'taabor-mobile-app',
    storageBucket: 'taabor-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEzT3EgCYgHqYJYLZXt8m07K1GvY-ZegY',
    appId: '1:332519555718:web:01604108868039b75c4707',
    messagingSenderId: '332519555718',
    projectId: 'taabor-mobile-app',
    authDomain: 'taabor-mobile-app.firebaseapp.com',
    storageBucket: 'taabor-mobile-app.firebasestorage.app',
    measurementId: 'G-74CN6DXKTV',
  );
}
