import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../home/data/models/business_model.dart';
import '../../../home/data/models/service_model.dart';
import '../../../home/data/repositories/business_repository_impl.dart';
import '../../domain/entities/ticket.dart';
import '../../presentation/bloc/queue_bloc.dart';
import '../../presentation/bloc/queue_event.dart';
import '../../presentation/bloc/queue_state.dart';
import '../../../../core/di/injection.dart';
import 'ticket_status_page.dart';
import 'package:provider/provider.dart';
import '../../../../core/providers/favorites_provider.dart';
import '../../../../features/chat/presentation/pages/chat_page.dart';
import '../../../../core/utils/whatsapp_helper.dart';

class BusinessDetailsPage extends StatelessWidget {
  final BusinessModel business;

  const BusinessDetailsPage({super.key, required this.business});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => sl<QueueBloc>(),
      child: BusinessDetailsView(business: business),
    );
  }
}

class BusinessDetailsView extends StatefulWidget {
  final BusinessModel business;

  const BusinessDetailsView({super.key, required this.business});

  @override
  State<BusinessDetailsView> createState() => _BusinessDetailsViewState();
}

class _BusinessDetailsViewState extends State<BusinessDetailsView> {
  final _businessRepository = BusinessRepositoryImpl(remoteDataSource: sl());
  late Future<List<ServiceModel>> _servicesFuture;
  ServiceModel? _selectedService;
  bool _isBooking = false;

  @override
  void initState() {
    super.initState();
    _servicesFuture = _loadServices();
  }

  Future<List<ServiceModel>> _loadServices() async {
    final result = await _businessRepository.getServicesForBusiness(
      widget.business.id,
    );
    return result.fold(
      (failure) => <ServiceModel>[],
      (services) => services
          .map(
            (s) => ServiceModel(
              id: s.id,
              name: s.name,
              durationMinutes: s.durationMinutes,
              price: s.price,
            ),
          )
          .toList(),
    );
  }

  void _bookTicket() {
    if (_selectedService == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('يرجى اختيار خدمة أولاً')));
      return;
    }

    final newTicket = Ticket(
      id: '', // Generated by Repo
      userId: FirebaseAuth.instance.currentUser?.uid ?? 'guest_user',
      businessId: widget.business.id,
      serviceName: _selectedService!.name,
      ticketNumber: widget.business.currentQueueLength + 1,
      status: TicketStatus.pending,
      type: TicketType.regular,
      createdAt: DateTime.now(),
    );

    context.read<QueueBloc>().add(AddTicketEvent(newTicket));
    setState(() {
      _isBooking = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.business.name),
        actions: [
          Consumer<FavoritesProvider>(
            builder: (context, favorites, _) {
              final isFav = favorites.isFavorite(widget.business.id);
              return IconButton(
                icon: Icon(isFav ? Icons.favorite : Icons.favorite_border),
                color: isFav ? Colors.red : null,
                onPressed: () => favorites.toggleFavorite(widget.business.id),
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.chat),
            onPressed: () {
              // Use a direct navigation for now, later maybe use named routes
              // We need to import ChatPage
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) {
                    final currentUser = FirebaseAuth.instance.currentUser;
                    final currentUserId = currentUser?.uid ?? 'guest';
                    // Generate a simplistic chat ID for MVP: user_business
                    final chatId = '${currentUserId}_${widget.business.id}';

                    return ChatPage(
                      chatId: chatId,
                      userId: currentUserId,
                      userName: currentUser?.displayName ?? 'Guest',
                    );
                  },
                ),
              );
            },
          ),
          IconButton(
            icon: const Icon(
              Icons.call,
              color: Colors.green,
            ), // Green for WhatsApp
            onPressed: () {
              WhatsAppHelper.openWhatsApp(
                context,
                widget.business.phoneNumber ?? '+9647500000000',
              ); // Use fallback if null
            },
          ),
        ],
      ),
      body: BlocListener<QueueBloc, QueueState>(
        listener: (context, state) {
          if (state is QueueError) {
            setState(() => _isBooking = false);
            ScaffoldMessenger.of(
              context,
            ).showSnackBar(SnackBar(content: Text(state.message)));
          } else if (state is QueueOperationSuccess) {
            setState(() => _isBooking = false);
            if (state.ticket != null) {
              Navigator.pushReplacement(
                context,
                MaterialPageRoute(
                  builder: (_) => TicketStatusPage(
                    ticket: state.ticket!,
                    businessName: widget.business.name,
                  ),
                ),
              );
            }
          }
        },
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Hero Image
                    Container(
                      height: 200,
                      width: double.infinity,
                      margin: const EdgeInsets.only(bottom: 16),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(12),
                        color: Colors.grey[300],
                      ),
                      clipBehavior: Clip.antiAlias,
                      child: Hero(
                        tag: 'business_image_${widget.business.id}',
                        child: widget.business.imageUrl.isNotEmpty
                            ? Image.network(
                                widget.business.imageUrl,
                                fit: BoxFit.cover,
                                errorBuilder: (context, error, stackTrace) {
                                  return const Center(
                                    child: Icon(
                                      Icons.store,
                                      size: 50,
                                      color: Colors.grey,
                                    ),
                                  );
                                },
                              )
                            : const Center(
                                child: Icon(
                                  Icons.store,
                                  size: 50,
                                  color: Colors.grey,
                                ),
                              ),
                      ),
                    ),
                    // Info Card
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(12),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.grey.withValues(alpha: 0.1),
                            blurRadius: 10,
                          ),
                        ],
                      ),
                      child: Column(
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceAround,
                            children: [
                              Column(
                                children: [
                                  Text(
                                    '${widget.business.currentQueueLength}',
                                    style: const TextStyle(
                                      fontSize: 24,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                  Text(
                                    'بالانتظار',
                                    style: TextStyle(
                                      color: Colors.grey[600],
                                      fontSize: 12,
                                    ),
                                  ),
                                ],
                              ),
                              Container(
                                height: 40,
                                width: 1,
                                color: Colors.grey[300],
                              ),
                              Column(
                                children: [
                                  Text(
                                    '${widget.business.estimatedWaitTimeMinutes} د',
                                    style: const TextStyle(
                                      fontSize: 24,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.blue,
                                    ),
                                  ),
                                  Text(
                                    'وقت تقريبي',
                                    style: TextStyle(
                                      color: Colors.grey[600],
                                      fontSize: 12,
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                    const Text(
                      'اختر الخدمة',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),

                    FutureBuilder<List<ServiceModel>>(
                      future: _servicesFuture,
                      builder: (context, snapshot) {
                        if (snapshot.connectionState ==
                            ConnectionState.waiting) {
                          return const Center(child: LinearProgressIndicator());
                        }

                        final services = snapshot.data ?? [];

                        return ListView.separated(
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          itemCount: services.length,
                          separatorBuilder: (_, __) =>
                              const SizedBox(height: 8),
                          itemBuilder: (context, index) {
                            final service = services[index];
                            final isSelected =
                                _selectedService?.id == service.id;

                            return InkWell(
                              onTap: () {
                                setState(() {
                                  _selectedService = service;
                                });
                              },
                              child: Container(
                                padding: const EdgeInsets.all(12),
                                decoration: BoxDecoration(
                                  color: isSelected
                                      ? Colors.deepPurple.withValues(alpha: 0.1)
                                      : Colors.white,
                                  border: Border.all(
                                    color: isSelected
                                        ? Colors.deepPurple
                                        : Colors.grey[300]!,
                                    width: isSelected ? 2 : 1,
                                  ),
                                  borderRadius: BorderRadius.circular(8),
                                ),
                                child: Row(
                                  children: [
                                    // Visual selection indicator
                                    Icon(
                                      isSelected
                                          ? Icons.radio_button_checked
                                          : Icons.radio_button_unchecked,
                                      color: isSelected
                                          ? Colors.deepPurple
                                          : Colors.grey[400],
                                    ),
                                    const SizedBox(width: 12),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            service.name,
                                            style: const TextStyle(
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                          Text(
                                            '${service.durationMinutes} دقيقة',
                                            style: TextStyle(
                                              color: Colors.grey[600],
                                              fontSize: 12,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text('${service.price} د.ع'),
                                  ],
                                ),
                              ),
                            );
                          },
                        );
                      },
                    ),
                  ],
                ),
              ),
            ),

            Container(
              padding: const EdgeInsets.all(16),
              decoration: const BoxDecoration(
                color: Colors.white,
                border: Border(top: BorderSide(color: Colors.black12)),
              ),
              child: SafeArea(
                child: SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: _isBooking ? null : _bookTicket,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.deepPurple,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                    ),
                    child: _isBooking
                        ? const CircularProgressIndicator(color: Colors.white)
                        : const Text(
                            'حجز دور (احصل على رقم)',
                            style: TextStyle(fontSize: 18, color: Colors.white),
                          ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
