// Mocks generated by Mockito 5.4.6 from annotations
// in taabor/test/widget/home_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i11;

import 'package:flutter/material.dart' as _i10;
import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:taabor/core/providers/theme_provider.dart' as _i9;
import 'package:taabor/features/home/domain/usecases/get_business_services.dart'
    as _i3;
import 'package:taabor/features/home/domain/usecases/get_businesses.dart'
    as _i2;
import 'package:taabor/features/home/presentation/bloc/business_bloc.dart'
    as _i5;
import 'package:taabor/features/home/presentation/bloc/business_event.dart'
    as _i7;
import 'package:taabor/features/home/presentation/bloc/business_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetBusinesses_0 extends _i1.SmartFake implements _i2.GetBusinesses {
  _FakeGetBusinesses_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetBusinessServices_1 extends _i1.SmartFake
    implements _i3.GetBusinessServices {
  _FakeGetBusinessServices_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBusinessState_2 extends _i1.SmartFake implements _i4.BusinessState {
  _FakeBusinessState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BusinessBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessBloc extends _i1.Mock implements _i5.BusinessBloc {
  MockBusinessBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetBusinesses get getBusinesses =>
      (super.noSuchMethod(
            Invocation.getter(#getBusinesses),
            returnValue: _FakeGetBusinesses_0(
              this,
              Invocation.getter(#getBusinesses),
            ),
          )
          as _i2.GetBusinesses);

  @override
  _i3.GetBusinessServices get getBusinessServices =>
      (super.noSuchMethod(
            Invocation.getter(#getBusinessServices),
            returnValue: _FakeGetBusinessServices_1(
              this,
              Invocation.getter(#getBusinessServices),
            ),
          )
          as _i3.GetBusinessServices);

  @override
  _i4.BusinessState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBusinessState_2(this, Invocation.getter(#state)),
          )
          as _i4.BusinessState);

  @override
  _i6.Stream<_i4.BusinessState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.BusinessState>.empty(),
          )
          as _i6.Stream<_i4.BusinessState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.BusinessEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.BusinessEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.BusinessState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.BusinessEvent>(
    _i8.EventHandler<E, _i4.BusinessState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i7.BusinessEvent, _i4.BusinessState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i4.BusinessState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i9.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i10.ThemeMode.system,
          )
          as _i10.ThemeMode);

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void toggleTheme() => super.noSuchMethod(
    Invocation.method(#toggleTheme, []),
    returnValueForMissingStub: null,
  );

  @override
  void setThemeMode(_i10.ThemeMode? mode) => super.noSuchMethod(
    Invocation.method(#setThemeMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
